name: Release WhisBergi

on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create Addon Directory
        run: |
          mkdir -p WhisBergi
          cp WhisBergi.lua WhisBergi/
          cp WhisBergi.toc WhisBergi/
          cp README.md WhisBergi/

      - name: Create Archive
        run: zip -r WhisBergi.zip WhisBergi

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: WhisBergi.zip
          fail_on_unmatched_files: true

      - name: Upload to CurseForge
        uses: itsmeow/curseforge-upload@v3
        with:
          file_path: WhisBergi.zip
          game_endpoint: wow
          game_versions: '4.4.2'
          release_type: release
          project_id: ${{ vars.CF_PROJECT_ID }}
          token: ${{ secrets.CF_API_TOKEN }}
          changelog: ${{ github.event.release.body }} # Use release notes as changelog
          changelog_type: markdown
          display_name: WhisBergi-${{ steps.get_version.outputs.VERSION }}
